services:
  backend:
    build:
      context: ../../
      dockerfile: docker/cd/backend/DockerFile
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_AUTH_DATABASE=${MYSQL_AUTH_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "${GO_PORT}:80"
    volumes:
      - ../../backend:/backend
      - session_data:/session_data
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
  frontend:
    build:
      context: ../../
      dockerfile: docker/cd/frontend/DockerFile
    ports:
      - "${VITE_PORT}:5173"
    volumes:
      - ../../frontend:/frontend
    stdin_open: true
    tty: true
  db:
    build:
      context: ../../
      dockerfile: docker/cd/db/DockerFile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_AUTH_DATABASE=${MYSQL_AUTH_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "localhost",
          "-u",
          "${MYSQL_USER}",
          "-p${MYSQL_PASSWORD}",
        ]
      interval: 2s
      timeout: 30s
      retries: 100
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    stdin_open: true
    tty: true
volumes:
  db_data:
  session_data:
