services:
  backend:
    build:
      context: ../../
      dockerfile: docker/cd/backend/DockerFile
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_AUTH_DATABASE=${MYSQL_AUTH_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "${GO_PORT}:80"
    volumes:
      - ../../backend:/backend
      - session_data:/session_data
    depends_on:
      - db
    stdin_open: true
    tty: true
  frontend:
    build:
      context: ../../
      dockerfile: docker/cd/frontend/DockerFile
    ports:
      - "${VITE_PORT}:5173"
    volumes:
      - ../../frontend:/frontend
    stdin_open: true
    tty: true
  db:
    build:
      context: ../../
      dockerfile: docker/cd/db/DockerFile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_AUTH_DATABASE=${MYSQL_AUTH_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    stdin_open: true
    tty: true
volumes:
  db_data:
  session_data:
